### ISSUE TITLE
Update the project structure

### ISSUE THREAD

**Issue by apepkuss** [WasmEdge/wasmedge-stable-diffusion#2]
The `src` directory is now under the `rust` directory. It would be better to remove the `rust` directory so that the `src` directory is under the root directory directly. This change will allow other rust projects to import the crate via the repo url. Thanks!

**Comment by hydai** [comment]
Hi @grorge123, Could you help fix this issue?

**Comment by hydai** [comment]
Hold on. I think the wasi-nn has the same structure without any issue: https://github.com/bytecodealliance/wasi-nn
What's the reason that we have to change to this one?
